@startuml Load Library
initiator -> LibManager : load_file(path)
activate LibManager
    LibManager -> LibManager : check & load
        alt
    LibManager -> Library : register_all()
    activate Library
        loop for each Component
            activate ComponentRegistrar
                Library -> ComponentRegistrar : register()
                alt
                    Library <- ComponentRegistrar : Success
                else
                    Library <- ComponentRegistrar : Failure
                end
            deactivate ComponentRegistrar
        end
        initiator <- Library : Success
    else
        initiator <- Library : Failure
    end
    deactivate Library
deactivate LibManager
@enduml